-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object exposing (..)


type ActivityLikeNotification
    = ActivityLikeNotification


type ActivityMentionNotification
    = ActivityMentionNotification


type ActivityMessageNotification
    = ActivityMessageNotification


type ActivityReply
    = ActivityReply


type ActivityReplyLikeNotification
    = ActivityReplyLikeNotification


type ActivityReplyNotification
    = ActivityReplyNotification


type ActivityReplySubscribedNotification
    = ActivityReplySubscribedNotification


type AiringNotification
    = AiringNotification


type AiringProgression
    = AiringProgression


type AiringSchedule
    = AiringSchedule


type AiringScheduleConnection
    = AiringScheduleConnection


type AiringScheduleEdge
    = AiringScheduleEdge


type AniChartUser
    = AniChartUser


type Character
    = Character


type CharacterConnection
    = CharacterConnection


type CharacterEdge
    = CharacterEdge


type CharacterImage
    = CharacterImage


type CharacterName
    = CharacterName


type CharacterSubmission
    = CharacterSubmission


type CharacterSubmissionConnection
    = CharacterSubmissionConnection


type CharacterSubmissionEdge
    = CharacterSubmissionEdge


type Deleted
    = Deleted


type Favourites
    = Favourites


type FollowingNotification
    = FollowingNotification


type FormatStats
    = FormatStats


type FuzzyDate
    = FuzzyDate


type GenreStats
    = GenreStats


type InternalPage
    = InternalPage


type ListActivity
    = ListActivity


type ListScoreStats
    = ListScoreStats


type Media
    = Media


type MediaCharacter
    = MediaCharacter


type MediaConnection
    = MediaConnection


type MediaCoverImage
    = MediaCoverImage


type MediaDataChangeNotification
    = MediaDataChangeNotification


type MediaDeletionNotification
    = MediaDeletionNotification


type MediaEdge
    = MediaEdge


type MediaExternalLink
    = MediaExternalLink


type MediaList
    = MediaList


type MediaListCollection
    = MediaListCollection


type MediaListGroup
    = MediaListGroup


type MediaListOptions
    = MediaListOptions


type MediaListTypeOptions
    = MediaListTypeOptions


type MediaMergeNotification
    = MediaMergeNotification


type MediaRank
    = MediaRank


type MediaStats
    = MediaStats


type MediaStreamingEpisode
    = MediaStreamingEpisode


type MediaSubmission
    = MediaSubmission


type MediaSubmissionComparison
    = MediaSubmissionComparison


type MediaSubmissionEdge
    = MediaSubmissionEdge


type MediaTag
    = MediaTag


type MediaTitle
    = MediaTitle


type MediaTrailer
    = MediaTrailer


type MediaTrend
    = MediaTrend


type MediaTrendConnection
    = MediaTrendConnection


type MediaTrendEdge
    = MediaTrendEdge


type MessageActivity
    = MessageActivity


type ModAction
    = ModAction


type NotificationOption
    = NotificationOption


type Page
    = Page


type PageInfo
    = PageInfo


type ParsedMarkdown
    = ParsedMarkdown


type Recommendation
    = Recommendation


type RecommendationConnection
    = RecommendationConnection


type RecommendationEdge
    = RecommendationEdge


type RelatedMediaAdditionNotification
    = RelatedMediaAdditionNotification


type Report
    = Report


type Review
    = Review


type ReviewConnection
    = ReviewConnection


type ReviewEdge
    = ReviewEdge


type RevisionHistory
    = RevisionHistory


type ScoreDistribution
    = ScoreDistribution


type SiteStatistics
    = SiteStatistics


type SiteTrend
    = SiteTrend


type SiteTrendConnection
    = SiteTrendConnection


type SiteTrendEdge
    = SiteTrendEdge


type Staff
    = Staff


type StaffConnection
    = StaffConnection


type StaffEdge
    = StaffEdge


type StaffImage
    = StaffImage


type StaffName
    = StaffName


type StaffRoleType
    = StaffRoleType


type StaffStats
    = StaffStats


type StaffSubmission
    = StaffSubmission


type StatusDistribution
    = StatusDistribution


type Studio
    = Studio


type StudioConnection
    = StudioConnection


type StudioEdge
    = StudioEdge


type StudioStats
    = StudioStats


type TagStats
    = TagStats


type TextActivity
    = TextActivity


type Thread
    = Thread


type ThreadCategory
    = ThreadCategory


type ThreadComment
    = ThreadComment


type ThreadCommentLikeNotification
    = ThreadCommentLikeNotification


type ThreadCommentMentionNotification
    = ThreadCommentMentionNotification


type ThreadCommentReplyNotification
    = ThreadCommentReplyNotification


type ThreadCommentSubscribedNotification
    = ThreadCommentSubscribedNotification


type ThreadLikeNotification
    = ThreadLikeNotification


type User
    = User


type UserActivityHistory
    = UserActivityHistory


type UserAvatar
    = UserAvatar


type UserCountryStatistic
    = UserCountryStatistic


type UserFormatStatistic
    = UserFormatStatistic


type UserGenreStatistic
    = UserGenreStatistic


type UserLengthStatistic
    = UserLengthStatistic


type UserModData
    = UserModData


type UserOptions
    = UserOptions


type UserPreviousName
    = UserPreviousName


type UserReleaseYearStatistic
    = UserReleaseYearStatistic


type UserScoreStatistic
    = UserScoreStatistic


type UserStaffStatistic
    = UserStaffStatistic


type UserStartYearStatistic
    = UserStartYearStatistic


type UserStatisticTypes
    = UserStatisticTypes


type UserStatistics
    = UserStatistics


type UserStats
    = UserStats


type UserStatusStatistic
    = UserStatusStatistic


type UserStudioStatistic
    = UserStudioStatistic


type UserTagStatistic
    = UserTagStatistic


type UserVoiceActorStatistic
    = UserVoiceActorStatistic


type YearStats
    = YearStats
