-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Scalar exposing (Codecs, CountryCode(..), FuzzyDateInt(..), Id(..), Json(..), defaultCodecs, defineCodecs, unwrapCodecs, unwrapEncoder)

import Graphql.Codec exposing (Codec)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode
import Json.Decode as Decode exposing (Decoder)
import Json.Encode as Encode


type CountryCode
    = CountryCode String


type FuzzyDateInt
    = FuzzyDateInt String


type Id
    = Id String


type Json
    = Json String


defineCodecs :
    { codecCountryCode : Codec valueCountryCode
    , codecFuzzyDateInt : Codec valueFuzzyDateInt
    , codecId : Codec valueId
    , codecJson : Codec valueJson
    }
    -> Codecs valueCountryCode valueFuzzyDateInt valueId valueJson
defineCodecs definitions =
    Codecs definitions


unwrapCodecs :
    Codecs valueCountryCode valueFuzzyDateInt valueId valueJson
    ->
        { codecCountryCode : Codec valueCountryCode
        , codecFuzzyDateInt : Codec valueFuzzyDateInt
        , codecId : Codec valueId
        , codecJson : Codec valueJson
        }
unwrapCodecs (Codecs unwrappedCodecs) =
    unwrappedCodecs


unwrapEncoder :
    (RawCodecs valueCountryCode valueFuzzyDateInt valueId valueJson -> Codec getterValue)
    -> Codecs valueCountryCode valueFuzzyDateInt valueId valueJson
    -> getterValue
    -> Graphql.Internal.Encode.Value
unwrapEncoder getter (Codecs unwrappedCodecs) =
    (unwrappedCodecs |> getter |> .encoder) >> Graphql.Internal.Encode.fromJson


type Codecs valueCountryCode valueFuzzyDateInt valueId valueJson
    = Codecs (RawCodecs valueCountryCode valueFuzzyDateInt valueId valueJson)


type alias RawCodecs valueCountryCode valueFuzzyDateInt valueId valueJson =
    { codecCountryCode : Codec valueCountryCode
    , codecFuzzyDateInt : Codec valueFuzzyDateInt
    , codecId : Codec valueId
    , codecJson : Codec valueJson
    }


defaultCodecs : RawCodecs CountryCode FuzzyDateInt Id Json
defaultCodecs =
    { codecCountryCode =
        { encoder = \(CountryCode raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map CountryCode
        }
    , codecFuzzyDateInt =
        { encoder = \(FuzzyDateInt raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map FuzzyDateInt
        }
    , codecId =
        { encoder = \(Id raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map Id
        }
    , codecJson =
        { encoder = \(Json raw) -> Encode.string raw
        , decoder = Object.scalarDecoder |> Decode.map Json
        }
    }
