-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Union exposing (..)


type ActivityUnion
    = ActivityUnion


type LikeableUnion
    = LikeableUnion


type NotificationUnion
    = NotificationUnion
