-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.ActivityMessageNotification exposing (..)

import AniList.Enum.NotificationType
import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The id of the Notification
-}
id : SelectionSet Int AniList.Object.ActivityMessageNotification
id =
    Object.selectionForField "Int" "id" [] Decode.int


{-| The if of the user who send the message
-}
userId : SelectionSet Int AniList.Object.ActivityMessageNotification
userId =
    Object.selectionForField "Int" "userId" [] Decode.int


{-| The type of notification
-}
type_ : SelectionSet (Maybe AniList.Enum.NotificationType.NotificationType) AniList.Object.ActivityMessageNotification
type_ =
    Object.selectionForField "(Maybe Enum.NotificationType.NotificationType)" "type" [] (AniList.Enum.NotificationType.decoder |> Decode.nullable)


{-| The id of the activity message
-}
activityId : SelectionSet Int AniList.Object.ActivityMessageNotification
activityId =
    Object.selectionForField "Int" "activityId" [] Decode.int


{-| The notification context text
-}
context : SelectionSet (Maybe String) AniList.Object.ActivityMessageNotification
context =
    Object.selectionForField "(Maybe String)" "context" [] (Decode.string |> Decode.nullable)


{-| The time the notification was created at
-}
createdAt : SelectionSet (Maybe Int) AniList.Object.ActivityMessageNotification
createdAt =
    Object.selectionForField "(Maybe Int)" "createdAt" [] (Decode.int |> Decode.nullable)


{-| The message activity
-}
message :
    SelectionSet decodesTo AniList.Object.MessageActivity
    -> SelectionSet (Maybe decodesTo) AniList.Object.ActivityMessageNotification
message object____ =
    Object.selectionForCompositeField "message" [] object____ (Basics.identity >> Decode.nullable)


{-| The user who sent the message
-}
user :
    SelectionSet decodesTo AniList.Object.User
    -> SelectionSet (Maybe decodesTo) AniList.Object.ActivityMessageNotification
user object____ =
    Object.selectionForCompositeField "user" [] object____ (Basics.identity >> Decode.nullable)
