-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.AiringScheduleEdge exposing (..)

import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


node :
    SelectionSet decodesTo AniList.Object.AiringSchedule
    -> SelectionSet (Maybe decodesTo) AniList.Object.AiringScheduleEdge
node object____ =
    Object.selectionForCompositeField "node" [] object____ (Basics.identity >> Decode.nullable)


{-| The id of the connection
-}
id : SelectionSet (Maybe Int) AniList.Object.AiringScheduleEdge
id =
    Object.selectionForField "(Maybe Int)" "id" [] (Decode.int |> Decode.nullable)
