-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.AiringNotification exposing (..)

import AniList.Enum.NotificationType
import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The id of the Notification
-}
id : SelectionSet Int AniList.Object.AiringNotification
id =
    Object.selectionForField "Int" "id" [] Decode.int


{-| The type of notification
-}
type_ : SelectionSet (Maybe AniList.Enum.NotificationType.NotificationType) AniList.Object.AiringNotification
type_ =
    Object.selectionForField "(Maybe Enum.NotificationType.NotificationType)" "type" [] (AniList.Enum.NotificationType.decoder |> Decode.nullable)


{-| The id of the aired anime
-}
animeId : SelectionSet Int AniList.Object.AiringNotification
animeId =
    Object.selectionForField "Int" "animeId" [] Decode.int


{-| The episode number that just aired
-}
episode : SelectionSet Int AniList.Object.AiringNotification
episode =
    Object.selectionForField "Int" "episode" [] Decode.int


{-| The notification context text
-}
contexts : SelectionSet (Maybe (List (Maybe String))) AniList.Object.AiringNotification
contexts =
    Object.selectionForField "(Maybe (List (Maybe String)))" "contexts" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| The time the notification was created at
-}
createdAt : SelectionSet (Maybe Int) AniList.Object.AiringNotification
createdAt =
    Object.selectionForField "(Maybe Int)" "createdAt" [] (Decode.int |> Decode.nullable)


{-| The associated media of the airing schedule
-}
media :
    SelectionSet decodesTo AniList.Object.Media
    -> SelectionSet (Maybe decodesTo) AniList.Object.AiringNotification
media object____ =
    Object.selectionForCompositeField "media" [] object____ (Basics.identity >> Decode.nullable)
