-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.CharacterImage exposing (..)

import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The character's image of media at its largest size
-}
large : SelectionSet (Maybe String) AniList.Object.CharacterImage
large =
    Object.selectionForField "(Maybe String)" "large" [] (Decode.string |> Decode.nullable)


{-| The character's image of media at medium size
-}
medium : SelectionSet (Maybe String) AniList.Object.CharacterImage
medium =
    Object.selectionForField "(Maybe String)" "medium" [] (Decode.string |> Decode.nullable)
