-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.FormatStats exposing (..)

import AniList.Enum.MediaFormat
import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


format : SelectionSet (Maybe AniList.Enum.MediaFormat.MediaFormat) AniList.Object.FormatStats
format =
    Object.selectionForField "(Maybe Enum.MediaFormat.MediaFormat)" "format" [] (AniList.Enum.MediaFormat.decoder |> Decode.nullable)


amount : SelectionSet (Maybe Int) AniList.Object.FormatStats
amount =
    Object.selectionForField "(Maybe Int)" "amount" [] (Decode.int |> Decode.nullable)
