-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.ListScoreStats exposing (..)

import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


meanScore : SelectionSet (Maybe Int) AniList.Object.ListScoreStats
meanScore =
    Object.selectionForField "(Maybe Int)" "meanScore" [] (Decode.int |> Decode.nullable)


standardDeviation : SelectionSet (Maybe Int) AniList.Object.ListScoreStats
standardDeviation =
    Object.selectionForField "(Maybe Int)" "standardDeviation" [] (Decode.int |> Decode.nullable)
