-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.ListActivity exposing (..)

import AniList.Enum.ActivityType
import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The id of the activity
-}
id : SelectionSet Int AniList.Object.ListActivity
id =
    Object.selectionForField "Int" "id" [] Decode.int


{-| The user id of the activity's creator
-}
userId : SelectionSet (Maybe Int) AniList.Object.ListActivity
userId =
    Object.selectionForField "(Maybe Int)" "userId" [] (Decode.int |> Decode.nullable)


{-| The type of activity
-}
type_ : SelectionSet (Maybe AniList.Enum.ActivityType.ActivityType) AniList.Object.ListActivity
type_ =
    Object.selectionForField "(Maybe Enum.ActivityType.ActivityType)" "type" [] (AniList.Enum.ActivityType.decoder |> Decode.nullable)


{-| The number of activity replies
-}
replyCount : SelectionSet Int AniList.Object.ListActivity
replyCount =
    Object.selectionForField "Int" "replyCount" [] Decode.int


{-| The list item's textual status
-}
status : SelectionSet (Maybe String) AniList.Object.ListActivity
status =
    Object.selectionForField "(Maybe String)" "status" [] (Decode.string |> Decode.nullable)


{-| The list progress made
-}
progress : SelectionSet (Maybe String) AniList.Object.ListActivity
progress =
    Object.selectionForField "(Maybe String)" "progress" [] (Decode.string |> Decode.nullable)


{-| If the activity is locked and can receive replies
-}
isLocked : SelectionSet (Maybe Bool) AniList.Object.ListActivity
isLocked =
    Object.selectionForField "(Maybe Bool)" "isLocked" [] (Decode.bool |> Decode.nullable)


{-| If the currently authenticated user is subscribed to the activity
-}
isSubscribed : SelectionSet (Maybe Bool) AniList.Object.ListActivity
isSubscribed =
    Object.selectionForField "(Maybe Bool)" "isSubscribed" [] (Decode.bool |> Decode.nullable)


{-| The amount of likes the activity has
-}
likeCount : SelectionSet Int AniList.Object.ListActivity
likeCount =
    Object.selectionForField "Int" "likeCount" [] Decode.int


{-| If the currently authenticated user liked the activity
-}
isLiked : SelectionSet (Maybe Bool) AniList.Object.ListActivity
isLiked =
    Object.selectionForField "(Maybe Bool)" "isLiked" [] (Decode.bool |> Decode.nullable)


{-| The url for the activity page on the AniList website
-}
siteUrl : SelectionSet (Maybe String) AniList.Object.ListActivity
siteUrl =
    Object.selectionForField "(Maybe String)" "siteUrl" [] (Decode.string |> Decode.nullable)


{-| The time the activity was created at
-}
createdAt : SelectionSet Int AniList.Object.ListActivity
createdAt =
    Object.selectionForField "Int" "createdAt" [] Decode.int


{-| The owner of the activity
-}
user :
    SelectionSet decodesTo AniList.Object.User
    -> SelectionSet (Maybe decodesTo) AniList.Object.ListActivity
user object____ =
    Object.selectionForCompositeField "user" [] object____ (Basics.identity >> Decode.nullable)


{-| The associated media to the activity update
-}
media :
    SelectionSet decodesTo AniList.Object.Media
    -> SelectionSet (Maybe decodesTo) AniList.Object.ListActivity
media object____ =
    Object.selectionForCompositeField "media" [] object____ (Basics.identity >> Decode.nullable)


{-| The written replies to the activity
-}
replies :
    SelectionSet decodesTo AniList.Object.ActivityReply
    -> SelectionSet (Maybe (List (Maybe decodesTo))) AniList.Object.ListActivity
replies object____ =
    Object.selectionForCompositeField "replies" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| The users who liked the activity
-}
likes :
    SelectionSet decodesTo AniList.Object.User
    -> SelectionSet (Maybe (List (Maybe decodesTo))) AniList.Object.ListActivity
likes object____ =
    Object.selectionForCompositeField "likes" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)
