-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.MediaExternalLink exposing (..)

import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The id of the external link
-}
id : SelectionSet Int AniList.Object.MediaExternalLink
id =
    Object.selectionForField "Int" "id" [] Decode.int


{-| The url of the external link
-}
url : SelectionSet String AniList.Object.MediaExternalLink
url =
    Object.selectionForField "String" "url" [] Decode.string


{-| The site location of the external link
-}
site : SelectionSet String AniList.Object.MediaExternalLink
site =
    Object.selectionForField "String" "site" [] Decode.string
