-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.MediaTrailer exposing (..)

import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The trailer video id
-}
id : SelectionSet (Maybe String) AniList.Object.MediaTrailer
id =
    Object.selectionForField "(Maybe String)" "id" [] (Decode.string |> Decode.nullable)


{-| The site the video is hosted by (Currently either youtube or dailymotion)
-}
site : SelectionSet (Maybe String) AniList.Object.MediaTrailer
site =
    Object.selectionForField "(Maybe String)" "site" [] (Decode.string |> Decode.nullable)


{-| The url for the thumbnail image of the video
-}
thumbnail : SelectionSet (Maybe String) AniList.Object.MediaTrailer
thumbnail =
    Object.selectionForField "(Maybe String)" "thumbnail" [] (Decode.string |> Decode.nullable)
