-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.MediaListGroup exposing (..)

import AniList.Enum.MediaListStatus
import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Media list entries
-}
entries :
    SelectionSet decodesTo AniList.Object.MediaList
    -> SelectionSet (Maybe (List (Maybe decodesTo))) AniList.Object.MediaListGroup
entries object____ =
    Object.selectionForCompositeField "entries" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


name : SelectionSet (Maybe String) AniList.Object.MediaListGroup
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


isCustomList : SelectionSet (Maybe Bool) AniList.Object.MediaListGroup
isCustomList =
    Object.selectionForField "(Maybe Bool)" "isCustomList" [] (Decode.bool |> Decode.nullable)


isSplitCompletedList : SelectionSet (Maybe Bool) AniList.Object.MediaListGroup
isSplitCompletedList =
    Object.selectionForField "(Maybe Bool)" "isSplitCompletedList" [] (Decode.bool |> Decode.nullable)


status : SelectionSet (Maybe AniList.Enum.MediaListStatus.MediaListStatus) AniList.Object.MediaListGroup
status =
    Object.selectionForField "(Maybe Enum.MediaListStatus.MediaListStatus)" "status" [] (AniList.Enum.MediaListStatus.decoder |> Decode.nullable)
