-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.MediaMergeNotification exposing (..)

import AniList.Enum.NotificationType
import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The id of the Notification
-}
id : SelectionSet Int AniList.Object.MediaMergeNotification
id =
    Object.selectionForField "Int" "id" [] Decode.int


{-| The type of notification
-}
type_ : SelectionSet (Maybe AniList.Enum.NotificationType.NotificationType) AniList.Object.MediaMergeNotification
type_ =
    Object.selectionForField "(Maybe Enum.NotificationType.NotificationType)" "type" [] (AniList.Enum.NotificationType.decoder |> Decode.nullable)


{-| The id of the media that was merged into
-}
mediaId : SelectionSet Int AniList.Object.MediaMergeNotification
mediaId =
    Object.selectionForField "Int" "mediaId" [] Decode.int


{-| The title of the deleted media
-}
deletedMediaTitles : SelectionSet (Maybe (List (Maybe String))) AniList.Object.MediaMergeNotification
deletedMediaTitles =
    Object.selectionForField "(Maybe (List (Maybe String)))" "deletedMediaTitles" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| The reason for the media data change
-}
context : SelectionSet (Maybe String) AniList.Object.MediaMergeNotification
context =
    Object.selectionForField "(Maybe String)" "context" [] (Decode.string |> Decode.nullable)


{-| The reason for the media merge
-}
reason : SelectionSet (Maybe String) AniList.Object.MediaMergeNotification
reason =
    Object.selectionForField "(Maybe String)" "reason" [] (Decode.string |> Decode.nullable)


{-| The time the notification was created at
-}
createdAt : SelectionSet (Maybe Int) AniList.Object.MediaMergeNotification
createdAt =
    Object.selectionForField "(Maybe Int)" "createdAt" [] (Decode.int |> Decode.nullable)


{-| The media that was merged into
-}
media :
    SelectionSet decodesTo AniList.Object.Media
    -> SelectionSet (Maybe decodesTo) AniList.Object.MediaMergeNotification
media object____ =
    Object.selectionForCompositeField "media" [] object____ (Basics.identity >> Decode.nullable)
