-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.MediaCoverImage exposing (..)

import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The cover image url of the media at its largest size. If this size isn't available, large will be provided instead.
-}
extraLarge : SelectionSet (Maybe String) AniList.Object.MediaCoverImage
extraLarge =
    Object.selectionForField "(Maybe String)" "extraLarge" [] (Decode.string |> Decode.nullable)


{-| The cover image url of the media at a large size
-}
large : SelectionSet (Maybe String) AniList.Object.MediaCoverImage
large =
    Object.selectionForField "(Maybe String)" "large" [] (Decode.string |> Decode.nullable)


{-| The cover image url of the media at medium size
-}
medium : SelectionSet (Maybe String) AniList.Object.MediaCoverImage
medium =
    Object.selectionForField "(Maybe String)" "medium" [] (Decode.string |> Decode.nullable)


{-| Average #hex color of cover image
-}
color : SelectionSet (Maybe String) AniList.Object.MediaCoverImage
color =
    Object.selectionForField "(Maybe String)" "color" [] (Decode.string |> Decode.nullable)
