-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.MediaStats exposing (..)

import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


scoreDistribution :
    SelectionSet decodesTo AniList.Object.ScoreDistribution
    -> SelectionSet (Maybe (List (Maybe decodesTo))) AniList.Object.MediaStats
scoreDistribution object____ =
    Object.selectionForCompositeField "scoreDistribution" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


statusDistribution :
    SelectionSet decodesTo AniList.Object.StatusDistribution
    -> SelectionSet (Maybe (List (Maybe decodesTo))) AniList.Object.MediaStats
statusDistribution object____ =
    Object.selectionForCompositeField "statusDistribution" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


airingProgression :
    SelectionSet decodesTo AniList.Object.AiringProgression
    -> SelectionSet (Maybe (List (Maybe decodesTo))) AniList.Object.MediaStats
airingProgression object____ =
    Object.selectionForCompositeField "airingProgression" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)
