-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.MediaCharacter exposing (..)

import AniList.Enum.CharacterRole
import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The id of the connection
-}
id : SelectionSet (Maybe Int) AniList.Object.MediaCharacter
id =
    Object.selectionForField "(Maybe Int)" "id" [] (Decode.int |> Decode.nullable)


{-| The characters role in the media
-}
role : SelectionSet (Maybe AniList.Enum.CharacterRole.CharacterRole) AniList.Object.MediaCharacter
role =
    Object.selectionForField "(Maybe Enum.CharacterRole.CharacterRole)" "role" [] (AniList.Enum.CharacterRole.decoder |> Decode.nullable)


roleNotes : SelectionSet (Maybe String) AniList.Object.MediaCharacter
roleNotes =
    Object.selectionForField "(Maybe String)" "roleNotes" [] (Decode.string |> Decode.nullable)


dubGroup : SelectionSet (Maybe String) AniList.Object.MediaCharacter
dubGroup =
    Object.selectionForField "(Maybe String)" "dubGroup" [] (Decode.string |> Decode.nullable)


{-| Media specific character name
-}
characterName : SelectionSet (Maybe String) AniList.Object.MediaCharacter
characterName =
    Object.selectionForField "(Maybe String)" "characterName" [] (Decode.string |> Decode.nullable)


{-| The characters in the media voiced by the parent actor
-}
character :
    SelectionSet decodesTo AniList.Object.Character
    -> SelectionSet (Maybe decodesTo) AniList.Object.MediaCharacter
character object____ =
    Object.selectionForCompositeField "character" [] object____ (Basics.identity >> Decode.nullable)


{-| The voice actor of the character
-}
voiceActor :
    SelectionSet decodesTo AniList.Object.Staff
    -> SelectionSet (Maybe decodesTo) AniList.Object.MediaCharacter
voiceActor object____ =
    Object.selectionForCompositeField "voiceActor" [] object____ (Basics.identity >> Decode.nullable)
