-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.MediaSubmission exposing (..)

import AniList.Enum.SubmissionStatus
import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The id of the submission
-}
id : SelectionSet Int AniList.Object.MediaSubmission
id =
    Object.selectionForField "Int" "id" [] Decode.int


{-| User submitter of the submission
-}
submitter :
    SelectionSet decodesTo AniList.Object.User
    -> SelectionSet (Maybe decodesTo) AniList.Object.MediaSubmission
submitter object____ =
    Object.selectionForCompositeField "submitter" [] object____ (Basics.identity >> Decode.nullable)


{-| Data Mod assigned to handle the submission
-}
assignee :
    SelectionSet decodesTo AniList.Object.User
    -> SelectionSet (Maybe decodesTo) AniList.Object.MediaSubmission
assignee object____ =
    Object.selectionForCompositeField "assignee" [] object____ (Basics.identity >> Decode.nullable)


{-| Status of the submission
-}
status : SelectionSet (Maybe AniList.Enum.SubmissionStatus.SubmissionStatus) AniList.Object.MediaSubmission
status =
    Object.selectionForField "(Maybe Enum.SubmissionStatus.SubmissionStatus)" "status" [] (AniList.Enum.SubmissionStatus.decoder |> Decode.nullable)


submitterStats : SelectionSet (Maybe AniList.ScalarCodecs.Json) AniList.Object.MediaSubmission
submitterStats =
    Object.selectionForField "(Maybe ScalarCodecs.Json)" "submitterStats" [] (AniList.ScalarCodecs.codecs |> AniList.Scalar.unwrapCodecs |> .codecJson |> .decoder |> Decode.nullable)


notes : SelectionSet (Maybe String) AniList.Object.MediaSubmission
notes =
    Object.selectionForField "(Maybe String)" "notes" [] (Decode.string |> Decode.nullable)


source : SelectionSet (Maybe String) AniList.Object.MediaSubmission
source =
    Object.selectionForField "(Maybe String)" "source" [] (Decode.string |> Decode.nullable)


changes : SelectionSet (Maybe (List (Maybe String))) AniList.Object.MediaSubmission
changes =
    Object.selectionForField "(Maybe (List (Maybe String)))" "changes" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| Whether the submission is locked
-}
locked : SelectionSet (Maybe Bool) AniList.Object.MediaSubmission
locked =
    Object.selectionForField "(Maybe Bool)" "locked" [] (Decode.bool |> Decode.nullable)


media :
    SelectionSet decodesTo AniList.Object.Media
    -> SelectionSet (Maybe decodesTo) AniList.Object.MediaSubmission
media object____ =
    Object.selectionForCompositeField "media" [] object____ (Basics.identity >> Decode.nullable)


submission :
    SelectionSet decodesTo AniList.Object.Media
    -> SelectionSet (Maybe decodesTo) AniList.Object.MediaSubmission
submission object____ =
    Object.selectionForCompositeField "submission" [] object____ (Basics.identity >> Decode.nullable)


characters :
    SelectionSet decodesTo AniList.Object.MediaSubmissionComparison
    -> SelectionSet (Maybe (List (Maybe decodesTo))) AniList.Object.MediaSubmission
characters object____ =
    Object.selectionForCompositeField "characters" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


staff :
    SelectionSet decodesTo AniList.Object.MediaSubmissionComparison
    -> SelectionSet (Maybe (List (Maybe decodesTo))) AniList.Object.MediaSubmission
staff object____ =
    Object.selectionForCompositeField "staff" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


studios :
    SelectionSet decodesTo AniList.Object.MediaSubmissionComparison
    -> SelectionSet (Maybe (List (Maybe decodesTo))) AniList.Object.MediaSubmission
studios object____ =
    Object.selectionForCompositeField "studios" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


relations :
    SelectionSet decodesTo AniList.Object.MediaEdge
    -> SelectionSet (Maybe (List (Maybe decodesTo))) AniList.Object.MediaSubmission
relations object____ =
    Object.selectionForCompositeField "relations" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


externalLinks :
    SelectionSet decodesTo AniList.Object.MediaExternalLink
    -> SelectionSet (Maybe (List (Maybe decodesTo))) AniList.Object.MediaSubmission
externalLinks object____ =
    Object.selectionForCompositeField "externalLinks" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


createdAt : SelectionSet (Maybe Int) AniList.Object.MediaSubmission
createdAt =
    Object.selectionForField "(Maybe Int)" "createdAt" [] (Decode.int |> Decode.nullable)
