-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.MediaListTypeOptions exposing (..)

import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The order each list should be displayed in
-}
sectionOrder : SelectionSet (Maybe (List (Maybe String))) AniList.Object.MediaListTypeOptions
sectionOrder =
    Object.selectionForField "(Maybe (List (Maybe String)))" "sectionOrder" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| If the completed sections of the list should be separated by format
-}
splitCompletedSectionByFormat : SelectionSet (Maybe Bool) AniList.Object.MediaListTypeOptions
splitCompletedSectionByFormat =
    Object.selectionForField "(Maybe Bool)" "splitCompletedSectionByFormat" [] (Decode.bool |> Decode.nullable)


{-| The list theme options
-}
theme : SelectionSet (Maybe AniList.ScalarCodecs.Json) AniList.Object.MediaListTypeOptions
theme =
    Object.selectionForField "(Maybe ScalarCodecs.Json)" "theme" [] (AniList.ScalarCodecs.codecs |> AniList.Scalar.unwrapCodecs |> .codecJson |> .decoder |> Decode.nullable)


{-| The names of the user's custom lists
-}
customLists : SelectionSet (Maybe (List (Maybe String))) AniList.Object.MediaListTypeOptions
customLists =
    Object.selectionForField "(Maybe (List (Maybe String)))" "customLists" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| The names of the user's advanced scoring sections
-}
advancedScoring : SelectionSet (Maybe (List (Maybe String))) AniList.Object.MediaListTypeOptions
advancedScoring =
    Object.selectionForField "(Maybe (List (Maybe String)))" "advancedScoring" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| If advanced scoring is enabled
-}
advancedScoringEnabled : SelectionSet (Maybe Bool) AniList.Object.MediaListTypeOptions
advancedScoringEnabled =
    Object.selectionForField "(Maybe Bool)" "advancedScoringEnabled" [] (Decode.bool |> Decode.nullable)
