-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.MediaTag exposing (..)

import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The id of the tag
-}
id : SelectionSet Int AniList.Object.MediaTag
id =
    Object.selectionForField "Int" "id" [] Decode.int


{-| The name of the tag
-}
name : SelectionSet String AniList.Object.MediaTag
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| A general description of the tag
-}
description : SelectionSet (Maybe String) AniList.Object.MediaTag
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| The categories of tags this tag belongs to
-}
category : SelectionSet (Maybe String) AniList.Object.MediaTag
category =
    Object.selectionForField "(Maybe String)" "category" [] (Decode.string |> Decode.nullable)


{-| The relevance ranking of the tag out of the 100 for this media
-}
rank : SelectionSet (Maybe Int) AniList.Object.MediaTag
rank =
    Object.selectionForField "(Maybe Int)" "rank" [] (Decode.int |> Decode.nullable)


{-| If the tag could be a spoiler for any media
-}
isGeneralSpoiler : SelectionSet (Maybe Bool) AniList.Object.MediaTag
isGeneralSpoiler =
    Object.selectionForField "(Maybe Bool)" "isGeneralSpoiler" [] (Decode.bool |> Decode.nullable)


{-| If the tag is a spoiler for this media
-}
isMediaSpoiler : SelectionSet (Maybe Bool) AniList.Object.MediaTag
isMediaSpoiler =
    Object.selectionForField "(Maybe Bool)" "isMediaSpoiler" [] (Decode.bool |> Decode.nullable)


{-| If the tag is only for adult 18+ media
-}
isAdult : SelectionSet (Maybe Bool) AniList.Object.MediaTag
isAdult =
    Object.selectionForField "(Maybe Bool)" "isAdult" [] (Decode.bool |> Decode.nullable)


{-| The user who submitted the tag
-}
userId : SelectionSet (Maybe Int) AniList.Object.MediaTag
userId =
    Object.selectionForField "(Maybe Int)" "userId" [] (Decode.int |> Decode.nullable)
