-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.Recommendation exposing (..)

import AniList.Enum.RecommendationRating
import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The id of the recommendation
-}
id : SelectionSet Int AniList.Object.Recommendation
id =
    Object.selectionForField "Int" "id" [] Decode.int


{-| Users rating of the recommendation
-}
rating : SelectionSet (Maybe Int) AniList.Object.Recommendation
rating =
    Object.selectionForField "(Maybe Int)" "rating" [] (Decode.int |> Decode.nullable)


{-| The rating of the recommendation by currently authenticated user
-}
userRating : SelectionSet (Maybe AniList.Enum.RecommendationRating.RecommendationRating) AniList.Object.Recommendation
userRating =
    Object.selectionForField "(Maybe Enum.RecommendationRating.RecommendationRating)" "userRating" [] (AniList.Enum.RecommendationRating.decoder |> Decode.nullable)


{-| The media the recommendation is from
-}
media :
    SelectionSet decodesTo AniList.Object.Media
    -> SelectionSet (Maybe decodesTo) AniList.Object.Recommendation
media object____ =
    Object.selectionForCompositeField "media" [] object____ (Basics.identity >> Decode.nullable)


{-| The recommended media
-}
mediaRecommendation :
    SelectionSet decodesTo AniList.Object.Media
    -> SelectionSet (Maybe decodesTo) AniList.Object.Recommendation
mediaRecommendation object____ =
    Object.selectionForCompositeField "mediaRecommendation" [] object____ (Basics.identity >> Decode.nullable)


{-| The user that first created the recommendation
-}
user :
    SelectionSet decodesTo AniList.Object.User
    -> SelectionSet (Maybe decodesTo) AniList.Object.Recommendation
user object____ =
    Object.selectionForCompositeField "user" [] object____ (Basics.identity >> Decode.nullable)
