-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.RelatedMediaAdditionNotification exposing (..)

import AniList.Enum.NotificationType
import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The id of the Notification
-}
id : SelectionSet Int AniList.Object.RelatedMediaAdditionNotification
id =
    Object.selectionForField "Int" "id" [] Decode.int


{-| The type of notification
-}
type_ : SelectionSet (Maybe AniList.Enum.NotificationType.NotificationType) AniList.Object.RelatedMediaAdditionNotification
type_ =
    Object.selectionForField "(Maybe Enum.NotificationType.NotificationType)" "type" [] (AniList.Enum.NotificationType.decoder |> Decode.nullable)


{-| The id of the new media
-}
mediaId : SelectionSet Int AniList.Object.RelatedMediaAdditionNotification
mediaId =
    Object.selectionForField "Int" "mediaId" [] Decode.int


{-| The notification context text
-}
context : SelectionSet (Maybe String) AniList.Object.RelatedMediaAdditionNotification
context =
    Object.selectionForField "(Maybe String)" "context" [] (Decode.string |> Decode.nullable)


{-| The time the notification was created at
-}
createdAt : SelectionSet (Maybe Int) AniList.Object.RelatedMediaAdditionNotification
createdAt =
    Object.selectionForField "(Maybe Int)" "createdAt" [] (Decode.int |> Decode.nullable)


{-| The associated media of the airing schedule
-}
media :
    SelectionSet decodesTo AniList.Object.Media
    -> SelectionSet (Maybe decodesTo) AniList.Object.RelatedMediaAdditionNotification
media object____ =
    Object.selectionForCompositeField "media" [] object____ (Basics.identity >> Decode.nullable)
