-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.RevisionHistory exposing (..)

import AniList.Enum.RevisionHistoryAction
import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The id of the media
-}
id : SelectionSet Int AniList.Object.RevisionHistory
id =
    Object.selectionForField "Int" "id" [] Decode.int


{-| The action taken on the objects
-}
action : SelectionSet (Maybe AniList.Enum.RevisionHistoryAction.RevisionHistoryAction) AniList.Object.RevisionHistory
action =
    Object.selectionForField "(Maybe Enum.RevisionHistoryAction.RevisionHistoryAction)" "action" [] (AniList.Enum.RevisionHistoryAction.decoder |> Decode.nullable)


{-| A JSON object of the fields that changed
-}
changes : SelectionSet (Maybe AniList.ScalarCodecs.Json) AniList.Object.RevisionHistory
changes =
    Object.selectionForField "(Maybe ScalarCodecs.Json)" "changes" [] (AniList.ScalarCodecs.codecs |> AniList.Scalar.unwrapCodecs |> .codecJson |> .decoder |> Decode.nullable)


{-| The user who made the edit to the object
-}
user :
    SelectionSet decodesTo AniList.Object.User
    -> SelectionSet (Maybe decodesTo) AniList.Object.RevisionHistory
user object____ =
    Object.selectionForCompositeField "user" [] object____ (Basics.identity >> Decode.nullable)


{-| The media the mod feed entry references
-}
media :
    SelectionSet decodesTo AniList.Object.Media
    -> SelectionSet (Maybe decodesTo) AniList.Object.RevisionHistory
media object____ =
    Object.selectionForCompositeField "media" [] object____ (Basics.identity >> Decode.nullable)


{-| The character the mod feed entry references
-}
character :
    SelectionSet decodesTo AniList.Object.Character
    -> SelectionSet (Maybe decodesTo) AniList.Object.RevisionHistory
character object____ =
    Object.selectionForCompositeField "character" [] object____ (Basics.identity >> Decode.nullable)


{-| The staff member the mod feed entry references
-}
staff :
    SelectionSet decodesTo AniList.Object.Staff
    -> SelectionSet (Maybe decodesTo) AniList.Object.RevisionHistory
staff object____ =
    Object.selectionForCompositeField "staff" [] object____ (Basics.identity >> Decode.nullable)


{-| The studio the mod feed entry references
-}
studio :
    SelectionSet decodesTo AniList.Object.Studio
    -> SelectionSet (Maybe decodesTo) AniList.Object.RevisionHistory
studio object____ =
    Object.selectionForCompositeField "studio" [] object____ (Basics.identity >> Decode.nullable)


{-| When the mod feed entry was created
-}
createdAt : SelectionSet (Maybe Int) AniList.Object.RevisionHistory
createdAt =
    Object.selectionForField "(Maybe Int)" "createdAt" [] (Decode.int |> Decode.nullable)
