-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.SiteTrend exposing (..)

import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The day the data was recorded (timestamp)
-}
date : SelectionSet Int AniList.Object.SiteTrend
date =
    Object.selectionForField "Int" "date" [] Decode.int


count : SelectionSet Int AniList.Object.SiteTrend
count =
    Object.selectionForField "Int" "count" [] Decode.int


{-| The change from yesterday
-}
change : SelectionSet Int AniList.Object.SiteTrend
change =
    Object.selectionForField "Int" "change" [] Decode.int
