-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.StaffSubmission exposing (..)

import AniList.Enum.SubmissionStatus
import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The id of the submission
-}
id : SelectionSet Int AniList.Object.StaffSubmission
id =
    Object.selectionForField "Int" "id" [] Decode.int


{-| Staff that the submission is referencing
-}
staff :
    SelectionSet decodesTo AniList.Object.Staff
    -> SelectionSet (Maybe decodesTo) AniList.Object.StaffSubmission
staff object____ =
    Object.selectionForCompositeField "staff" [] object____ (Basics.identity >> Decode.nullable)


{-| The staff submission changes
-}
submission :
    SelectionSet decodesTo AniList.Object.Staff
    -> SelectionSet (Maybe decodesTo) AniList.Object.StaffSubmission
submission object____ =
    Object.selectionForCompositeField "submission" [] object____ (Basics.identity >> Decode.nullable)


{-| Submitter for the submission
-}
submitter :
    SelectionSet decodesTo AniList.Object.User
    -> SelectionSet (Maybe decodesTo) AniList.Object.StaffSubmission
submitter object____ =
    Object.selectionForCompositeField "submitter" [] object____ (Basics.identity >> Decode.nullable)


{-| Data Mod assigned to handle the submission
-}
assignee :
    SelectionSet decodesTo AniList.Object.User
    -> SelectionSet (Maybe decodesTo) AniList.Object.StaffSubmission
assignee object____ =
    Object.selectionForCompositeField "assignee" [] object____ (Basics.identity >> Decode.nullable)


{-| Status of the submission
-}
status : SelectionSet (Maybe AniList.Enum.SubmissionStatus.SubmissionStatus) AniList.Object.StaffSubmission
status =
    Object.selectionForField "(Maybe Enum.SubmissionStatus.SubmissionStatus)" "status" [] (AniList.Enum.SubmissionStatus.decoder |> Decode.nullable)


{-| Inner details of submission status
-}
notes : SelectionSet (Maybe String) AniList.Object.StaffSubmission
notes =
    Object.selectionForField "(Maybe String)" "notes" [] (Decode.string |> Decode.nullable)


source : SelectionSet (Maybe String) AniList.Object.StaffSubmission
source =
    Object.selectionForField "(Maybe String)" "source" [] (Decode.string |> Decode.nullable)


{-| Whether the submission is locked
-}
locked : SelectionSet (Maybe Bool) AniList.Object.StaffSubmission
locked =
    Object.selectionForField "(Maybe Bool)" "locked" [] (Decode.bool |> Decode.nullable)


createdAt : SelectionSet (Maybe Int) AniList.Object.StaffSubmission
createdAt =
    Object.selectionForField "(Maybe Int)" "createdAt" [] (Decode.int |> Decode.nullable)
