-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.StaffStats exposing (..)

import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


staff :
    SelectionSet decodesTo AniList.Object.Staff
    -> SelectionSet (Maybe decodesTo) AniList.Object.StaffStats
staff object____ =
    Object.selectionForCompositeField "staff" [] object____ (Basics.identity >> Decode.nullable)


amount : SelectionSet (Maybe Int) AniList.Object.StaffStats
amount =
    Object.selectionForField "(Maybe Int)" "amount" [] (Decode.int |> Decode.nullable)


meanScore : SelectionSet (Maybe Int) AniList.Object.StaffStats
meanScore =
    Object.selectionForField "(Maybe Int)" "meanScore" [] (Decode.int |> Decode.nullable)


{-| The amount of time in minutes the staff member has been watched by the user
-}
timeWatched : SelectionSet (Maybe Int) AniList.Object.StaffStats
timeWatched =
    Object.selectionForField "(Maybe Int)" "timeWatched" [] (Decode.int |> Decode.nullable)
