-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.TagStats exposing (..)

import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


tag :
    SelectionSet decodesTo AniList.Object.MediaTag
    -> SelectionSet (Maybe decodesTo) AniList.Object.TagStats
tag object____ =
    Object.selectionForCompositeField "tag" [] object____ (Basics.identity >> Decode.nullable)


amount : SelectionSet (Maybe Int) AniList.Object.TagStats
amount =
    Object.selectionForField "(Maybe Int)" "amount" [] (Decode.int |> Decode.nullable)


meanScore : SelectionSet (Maybe Int) AniList.Object.TagStats
meanScore =
    Object.selectionForField "(Maybe Int)" "meanScore" [] (Decode.int |> Decode.nullable)


{-| The amount of time in minutes the tag has been watched by the user
-}
timeWatched : SelectionSet (Maybe Int) AniList.Object.TagStats
timeWatched =
    Object.selectionForField "(Maybe Int)" "timeWatched" [] (Decode.int |> Decode.nullable)
