-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.ThreadCommentLikeNotification exposing (..)

import AniList.Enum.NotificationType
import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The id of the Notification
-}
id : SelectionSet Int AniList.Object.ThreadCommentLikeNotification
id =
    Object.selectionForField "Int" "id" [] Decode.int


{-| The id of the user who liked to the activity
-}
userId : SelectionSet Int AniList.Object.ThreadCommentLikeNotification
userId =
    Object.selectionForField "Int" "userId" [] Decode.int


{-| The type of notification
-}
type_ : SelectionSet (Maybe AniList.Enum.NotificationType.NotificationType) AniList.Object.ThreadCommentLikeNotification
type_ =
    Object.selectionForField "(Maybe Enum.NotificationType.NotificationType)" "type" [] (AniList.Enum.NotificationType.decoder |> Decode.nullable)


{-| The id of the activity which was liked
-}
commentId : SelectionSet Int AniList.Object.ThreadCommentLikeNotification
commentId =
    Object.selectionForField "Int" "commentId" [] Decode.int


{-| The notification context text
-}
context : SelectionSet (Maybe String) AniList.Object.ThreadCommentLikeNotification
context =
    Object.selectionForField "(Maybe String)" "context" [] (Decode.string |> Decode.nullable)


{-| The time the notification was created at
-}
createdAt : SelectionSet (Maybe Int) AniList.Object.ThreadCommentLikeNotification
createdAt =
    Object.selectionForField "(Maybe Int)" "createdAt" [] (Decode.int |> Decode.nullable)


{-| The thread that the relevant comment belongs to
-}
thread :
    SelectionSet decodesTo AniList.Object.Thread
    -> SelectionSet (Maybe decodesTo) AniList.Object.ThreadCommentLikeNotification
thread object____ =
    Object.selectionForCompositeField "thread" [] object____ (Basics.identity >> Decode.nullable)


{-| The thread comment that was liked
-}
comment :
    SelectionSet decodesTo AniList.Object.ThreadComment
    -> SelectionSet (Maybe decodesTo) AniList.Object.ThreadCommentLikeNotification
comment object____ =
    Object.selectionForCompositeField "comment" [] object____ (Basics.identity >> Decode.nullable)


{-| The user who liked the activity
-}
user :
    SelectionSet decodesTo AniList.Object.User
    -> SelectionSet (Maybe decodesTo) AniList.Object.ThreadCommentLikeNotification
user object____ =
    Object.selectionForCompositeField "user" [] object____ (Basics.identity >> Decode.nullable)
