-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.ThreadCommentSubscribedNotification exposing (..)

import AniList.Enum.NotificationType
import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The id of the Notification
-}
id : SelectionSet Int AniList.Object.ThreadCommentSubscribedNotification
id =
    Object.selectionForField "Int" "id" [] Decode.int


{-| The id of the user who commented on the thread
-}
userId : SelectionSet Int AniList.Object.ThreadCommentSubscribedNotification
userId =
    Object.selectionForField "Int" "userId" [] Decode.int


{-| The type of notification
-}
type_ : SelectionSet (Maybe AniList.Enum.NotificationType.NotificationType) AniList.Object.ThreadCommentSubscribedNotification
type_ =
    Object.selectionForField "(Maybe Enum.NotificationType.NotificationType)" "type" [] (AniList.Enum.NotificationType.decoder |> Decode.nullable)


{-| The id of the new comment in the subscribed thread
-}
commentId : SelectionSet Int AniList.Object.ThreadCommentSubscribedNotification
commentId =
    Object.selectionForField "Int" "commentId" [] Decode.int


{-| The notification context text
-}
context : SelectionSet (Maybe String) AniList.Object.ThreadCommentSubscribedNotification
context =
    Object.selectionForField "(Maybe String)" "context" [] (Decode.string |> Decode.nullable)


{-| The time the notification was created at
-}
createdAt : SelectionSet (Maybe Int) AniList.Object.ThreadCommentSubscribedNotification
createdAt =
    Object.selectionForField "(Maybe Int)" "createdAt" [] (Decode.int |> Decode.nullable)


{-| The thread that the relevant comment belongs to
-}
thread :
    SelectionSet decodesTo AniList.Object.Thread
    -> SelectionSet (Maybe decodesTo) AniList.Object.ThreadCommentSubscribedNotification
thread object____ =
    Object.selectionForCompositeField "thread" [] object____ (Basics.identity >> Decode.nullable)


{-| The reply thread comment
-}
comment :
    SelectionSet decodesTo AniList.Object.ThreadComment
    -> SelectionSet (Maybe decodesTo) AniList.Object.ThreadCommentSubscribedNotification
comment object____ =
    Object.selectionForCompositeField "comment" [] object____ (Basics.identity >> Decode.nullable)


{-| The user who replied to the subscribed thread
-}
user :
    SelectionSet decodesTo AniList.Object.User
    -> SelectionSet (Maybe decodesTo) AniList.Object.ThreadCommentSubscribedNotification
user object____ =
    Object.selectionForCompositeField "user" [] object____ (Basics.identity >> Decode.nullable)
