-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.UserStartYearStatistic exposing (..)

import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


count : SelectionSet Int AniList.Object.UserStartYearStatistic
count =
    Object.selectionForField "Int" "count" [] Decode.int


meanScore : SelectionSet Float AniList.Object.UserStartYearStatistic
meanScore =
    Object.selectionForField "Float" "meanScore" [] Decode.float


minutesWatched : SelectionSet Int AniList.Object.UserStartYearStatistic
minutesWatched =
    Object.selectionForField "Int" "minutesWatched" [] Decode.int


chaptersRead : SelectionSet Int AniList.Object.UserStartYearStatistic
chaptersRead =
    Object.selectionForField "Int" "chaptersRead" [] Decode.int


mediaIds : SelectionSet (List (Maybe Int)) AniList.Object.UserStartYearStatistic
mediaIds =
    Object.selectionForField "(List (Maybe Int))" "mediaIds" [] (Decode.int |> Decode.nullable |> Decode.list)


startYear : SelectionSet (Maybe Int) AniList.Object.UserStartYearStatistic
startYear =
    Object.selectionForField "(Maybe Int)" "startYear" [] (Decode.int |> Decode.nullable)
