-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.UserStatisticTypes exposing (..)

import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


anime :
    SelectionSet decodesTo AniList.Object.UserStatistics
    -> SelectionSet (Maybe decodesTo) AniList.Object.UserStatisticTypes
anime object____ =
    Object.selectionForCompositeField "anime" [] object____ (Basics.identity >> Decode.nullable)


manga :
    SelectionSet decodesTo AniList.Object.UserStatistics
    -> SelectionSet (Maybe decodesTo) AniList.Object.UserStatisticTypes
manga object____ =
    Object.selectionForCompositeField "manga" [] object____ (Basics.identity >> Decode.nullable)
