-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Object.UserStudioStatistic exposing (..)

import AniList.InputObject
import AniList.Interface
import AniList.Object
import AniList.Scalar
import AniList.ScalarCodecs
import AniList.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


count : SelectionSet Int AniList.Object.UserStudioStatistic
count =
    Object.selectionForField "Int" "count" [] Decode.int


meanScore : SelectionSet Float AniList.Object.UserStudioStatistic
meanScore =
    Object.selectionForField "Float" "meanScore" [] Decode.float


minutesWatched : SelectionSet Int AniList.Object.UserStudioStatistic
minutesWatched =
    Object.selectionForField "Int" "minutesWatched" [] Decode.int


chaptersRead : SelectionSet Int AniList.Object.UserStudioStatistic
chaptersRead =
    Object.selectionForField "Int" "chaptersRead" [] Decode.int


mediaIds : SelectionSet (List (Maybe Int)) AniList.Object.UserStudioStatistic
mediaIds =
    Object.selectionForField "(List (Maybe Int))" "mediaIds" [] (Decode.int |> Decode.nullable |> Decode.list)


studio :
    SelectionSet decodesTo AniList.Object.Studio
    -> SelectionSet (Maybe decodesTo) AniList.Object.UserStudioStatistic
studio object____ =
    Object.selectionForCompositeField "studio" [] object____ (Basics.identity >> Decode.nullable)
