-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Enum.MediaSort exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| Media sort enums
-}
type MediaSort
    = Id
    | IdDesc
    | TitleRomaji
    | TitleRomajiDesc
    | TitleEnglish
    | TitleEnglishDesc
    | TitleNative
    | TitleNativeDesc
    | Type
    | TypeDesc
    | Format
    | FormatDesc
    | StartDate
    | StartDateDesc
    | EndDate
    | EndDateDesc
    | Score
    | ScoreDesc
    | Popularity
    | PopularityDesc
    | Trending
    | TrendingDesc
    | Episodes
    | EpisodesDesc
    | Duration
    | DurationDesc
    | Status
    | StatusDesc
    | Chapters
    | ChaptersDesc
    | Volumes
    | VolumesDesc
    | UpdatedAt
    | UpdatedAtDesc
    | SearchMatch
    | Favourites
    | FavouritesDesc


list : List MediaSort
list =
    [ Id, IdDesc, TitleRomaji, TitleRomajiDesc, TitleEnglish, TitleEnglishDesc, TitleNative, TitleNativeDesc, Type, TypeDesc, Format, FormatDesc, StartDate, StartDateDesc, EndDate, EndDateDesc, Score, ScoreDesc, Popularity, PopularityDesc, Trending, TrendingDesc, Episodes, EpisodesDesc, Duration, DurationDesc, Status, StatusDesc, Chapters, ChaptersDesc, Volumes, VolumesDesc, UpdatedAt, UpdatedAtDesc, SearchMatch, Favourites, FavouritesDesc ]


decoder : Decoder MediaSort
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "ID" ->
                        Decode.succeed Id

                    "ID_DESC" ->
                        Decode.succeed IdDesc

                    "TITLE_ROMAJI" ->
                        Decode.succeed TitleRomaji

                    "TITLE_ROMAJI_DESC" ->
                        Decode.succeed TitleRomajiDesc

                    "TITLE_ENGLISH" ->
                        Decode.succeed TitleEnglish

                    "TITLE_ENGLISH_DESC" ->
                        Decode.succeed TitleEnglishDesc

                    "TITLE_NATIVE" ->
                        Decode.succeed TitleNative

                    "TITLE_NATIVE_DESC" ->
                        Decode.succeed TitleNativeDesc

                    "TYPE" ->
                        Decode.succeed Type

                    "TYPE_DESC" ->
                        Decode.succeed TypeDesc

                    "FORMAT" ->
                        Decode.succeed Format

                    "FORMAT_DESC" ->
                        Decode.succeed FormatDesc

                    "START_DATE" ->
                        Decode.succeed StartDate

                    "START_DATE_DESC" ->
                        Decode.succeed StartDateDesc

                    "END_DATE" ->
                        Decode.succeed EndDate

                    "END_DATE_DESC" ->
                        Decode.succeed EndDateDesc

                    "SCORE" ->
                        Decode.succeed Score

                    "SCORE_DESC" ->
                        Decode.succeed ScoreDesc

                    "POPULARITY" ->
                        Decode.succeed Popularity

                    "POPULARITY_DESC" ->
                        Decode.succeed PopularityDesc

                    "TRENDING" ->
                        Decode.succeed Trending

                    "TRENDING_DESC" ->
                        Decode.succeed TrendingDesc

                    "EPISODES" ->
                        Decode.succeed Episodes

                    "EPISODES_DESC" ->
                        Decode.succeed EpisodesDesc

                    "DURATION" ->
                        Decode.succeed Duration

                    "DURATION_DESC" ->
                        Decode.succeed DurationDesc

                    "STATUS" ->
                        Decode.succeed Status

                    "STATUS_DESC" ->
                        Decode.succeed StatusDesc

                    "CHAPTERS" ->
                        Decode.succeed Chapters

                    "CHAPTERS_DESC" ->
                        Decode.succeed ChaptersDesc

                    "VOLUMES" ->
                        Decode.succeed Volumes

                    "VOLUMES_DESC" ->
                        Decode.succeed VolumesDesc

                    "UPDATED_AT" ->
                        Decode.succeed UpdatedAt

                    "UPDATED_AT_DESC" ->
                        Decode.succeed UpdatedAtDesc

                    "SEARCH_MATCH" ->
                        Decode.succeed SearchMatch

                    "FAVOURITES" ->
                        Decode.succeed Favourites

                    "FAVOURITES_DESC" ->
                        Decode.succeed FavouritesDesc

                    _ ->
                        Decode.fail ("Invalid MediaSort type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : MediaSort -> String
toString enum____ =
    case enum____ of
        Id ->
            "ID"

        IdDesc ->
            "ID_DESC"

        TitleRomaji ->
            "TITLE_ROMAJI"

        TitleRomajiDesc ->
            "TITLE_ROMAJI_DESC"

        TitleEnglish ->
            "TITLE_ENGLISH"

        TitleEnglishDesc ->
            "TITLE_ENGLISH_DESC"

        TitleNative ->
            "TITLE_NATIVE"

        TitleNativeDesc ->
            "TITLE_NATIVE_DESC"

        Type ->
            "TYPE"

        TypeDesc ->
            "TYPE_DESC"

        Format ->
            "FORMAT"

        FormatDesc ->
            "FORMAT_DESC"

        StartDate ->
            "START_DATE"

        StartDateDesc ->
            "START_DATE_DESC"

        EndDate ->
            "END_DATE"

        EndDateDesc ->
            "END_DATE_DESC"

        Score ->
            "SCORE"

        ScoreDesc ->
            "SCORE_DESC"

        Popularity ->
            "POPULARITY"

        PopularityDesc ->
            "POPULARITY_DESC"

        Trending ->
            "TRENDING"

        TrendingDesc ->
            "TRENDING_DESC"

        Episodes ->
            "EPISODES"

        EpisodesDesc ->
            "EPISODES_DESC"

        Duration ->
            "DURATION"

        DurationDesc ->
            "DURATION_DESC"

        Status ->
            "STATUS"

        StatusDesc ->
            "STATUS_DESC"

        Chapters ->
            "CHAPTERS"

        ChaptersDesc ->
            "CHAPTERS_DESC"

        Volumes ->
            "VOLUMES"

        VolumesDesc ->
            "VOLUMES_DESC"

        UpdatedAt ->
            "UPDATED_AT"

        UpdatedAtDesc ->
            "UPDATED_AT_DESC"

        SearchMatch ->
            "SEARCH_MATCH"

        Favourites ->
            "FAVOURITES"

        FavouritesDesc ->
            "FAVOURITES_DESC"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe MediaSort
fromString enumString____ =
    case enumString____ of
        "ID" ->
            Just Id

        "ID_DESC" ->
            Just IdDesc

        "TITLE_ROMAJI" ->
            Just TitleRomaji

        "TITLE_ROMAJI_DESC" ->
            Just TitleRomajiDesc

        "TITLE_ENGLISH" ->
            Just TitleEnglish

        "TITLE_ENGLISH_DESC" ->
            Just TitleEnglishDesc

        "TITLE_NATIVE" ->
            Just TitleNative

        "TITLE_NATIVE_DESC" ->
            Just TitleNativeDesc

        "TYPE" ->
            Just Type

        "TYPE_DESC" ->
            Just TypeDesc

        "FORMAT" ->
            Just Format

        "FORMAT_DESC" ->
            Just FormatDesc

        "START_DATE" ->
            Just StartDate

        "START_DATE_DESC" ->
            Just StartDateDesc

        "END_DATE" ->
            Just EndDate

        "END_DATE_DESC" ->
            Just EndDateDesc

        "SCORE" ->
            Just Score

        "SCORE_DESC" ->
            Just ScoreDesc

        "POPULARITY" ->
            Just Popularity

        "POPULARITY_DESC" ->
            Just PopularityDesc

        "TRENDING" ->
            Just Trending

        "TRENDING_DESC" ->
            Just TrendingDesc

        "EPISODES" ->
            Just Episodes

        "EPISODES_DESC" ->
            Just EpisodesDesc

        "DURATION" ->
            Just Duration

        "DURATION_DESC" ->
            Just DurationDesc

        "STATUS" ->
            Just Status

        "STATUS_DESC" ->
            Just StatusDesc

        "CHAPTERS" ->
            Just Chapters

        "CHAPTERS_DESC" ->
            Just ChaptersDesc

        "VOLUMES" ->
            Just Volumes

        "VOLUMES_DESC" ->
            Just VolumesDesc

        "UPDATED_AT" ->
            Just UpdatedAt

        "UPDATED_AT_DESC" ->
            Just UpdatedAtDesc

        "SEARCH_MATCH" ->
            Just SearchMatch

        "FAVOURITES" ->
            Just Favourites

        "FAVOURITES_DESC" ->
            Just FavouritesDesc

        _ ->
            Nothing
