-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Enum.RecommendationSort exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| Recommendation sort enums
-}
type RecommendationSort
    = Id
    | IdDesc
    | Rating
    | RatingDesc


list : List RecommendationSort
list =
    [ Id, IdDesc, Rating, RatingDesc ]


decoder : Decoder RecommendationSort
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "ID" ->
                        Decode.succeed Id

                    "ID_DESC" ->
                        Decode.succeed IdDesc

                    "RATING" ->
                        Decode.succeed Rating

                    "RATING_DESC" ->
                        Decode.succeed RatingDesc

                    _ ->
                        Decode.fail ("Invalid RecommendationSort type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : RecommendationSort -> String
toString enum____ =
    case enum____ of
        Id ->
            "ID"

        IdDesc ->
            "ID_DESC"

        Rating ->
            "RATING"

        RatingDesc ->
            "RATING_DESC"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe RecommendationSort
fromString enumString____ =
    case enumString____ of
        "ID" ->
            Just Id

        "ID_DESC" ->
            Just IdDesc

        "RATING" ->
            Just Rating

        "RATING_DESC" ->
            Just RatingDesc

        _ ->
            Nothing
