-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module AniList.Enum.SubmissionStatus exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| Submission status
-}
type SubmissionStatus
    = Pending
    | Rejected
    | PartiallyAccepted
    | Accepted


list : List SubmissionStatus
list =
    [ Pending, Rejected, PartiallyAccepted, Accepted ]


decoder : Decoder SubmissionStatus
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "PENDING" ->
                        Decode.succeed Pending

                    "REJECTED" ->
                        Decode.succeed Rejected

                    "PARTIALLY_ACCEPTED" ->
                        Decode.succeed PartiallyAccepted

                    "ACCEPTED" ->
                        Decode.succeed Accepted

                    _ ->
                        Decode.fail ("Invalid SubmissionStatus type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : SubmissionStatus -> String
toString enum____ =
    case enum____ of
        Pending ->
            "PENDING"

        Rejected ->
            "REJECTED"

        PartiallyAccepted ->
            "PARTIALLY_ACCEPTED"

        Accepted ->
            "ACCEPTED"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe SubmissionStatus
fromString enumString____ =
    case enumString____ of
        "PENDING" ->
            Just Pending

        "REJECTED" ->
            Just Rejected

        "PARTIALLY_ACCEPTED" ->
            Just PartiallyAccepted

        "ACCEPTED" ->
            Just Accepted

        _ ->
            Nothing
